USE OSRH;
GO
DROP TABLE IF EXISTS TRIP_SEGMENT;
DROP TABLE IF EXISTS TRIP_VEHICLE_MATCH;
DROP TABLE IF EXISTS PAYMENT_TRANSACTION;
DROP TABLE IF EXISTS TRIP;
DROP TABLE IF EXISTS SERVICE_CATALOG;
DROP TABLE IF EXISTS DRIVER_DOCUMENT;
DROP TABLE IF EXISTS DRIVER_DOC_TYPE;
DROP TABLE IF EXISTS USER_PAYMENT_METHOD;
DROP TABLE IF EXISTS USER_PREFERENCES;
DROP TABLE IF EXISTS AUTHENTICATION;
DROP TABLE IF EXISTS GDPR_LOG;
DROP TABLE IF EXISTS VEHICLE_DOCUMENT;
DROP TABLE IF EXISTS VEHICLE_DOC_TYPE;
DROP TABLE IF EXISTS VEHICLE_PHOTO;
DROP TABLE IF EXISTS VEHICLE_LOCATION;
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS DRIVER;
DROP TABLE IF EXISTS BRIDGE_REGION_MAP;
DROP TABLE IF EXISTS GEOFENCE_REGION;
DROP TABLE IF EXISTS BRIDGE_POINT;
DROP TABLE IF EXISTS VEHICLE_REQUIREMENTS;
DROP TABLE IF EXISTS SERVICE_TYPE;
DROP TABLE IF EXISTS [USER];
DROP TABLE IF EXISTS USER_TYPE;



CREATE TABLE USER_TYPE
(
  Type_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY(Type_Name)
);

CREATE TABLE [USER]
(
  User_ID INT IDENTITY(1,1) NOT NULL,
  First_Name VARCHAR(30) NOT NULL,
  Last_Name VARCHAR(30) NOT NULL,
  Birth_Date DATE NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Address VARCHAR(30) NOT NULL,
  Gender VARCHAR(10) NOT NULL,
  Type_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (User_ID),
  FOREIGN KEY (Type_Name) REFERENCES [USER_TYPE](Type_Name)
);

CREATE TABLE AUTHENTICATION
(
  Username VARCHAR(30) NOT NULL,
  Password_Hash VARBINARY(64) NOT NULL,
  User_ID INT NOT NULL,
  PRIMARY KEY (Username),
  FOREIGN KEY (User_ID) REFERENCES [USER](User_ID),
  CONSTRAINT UQ_Auth_User UNIQUE(User_ID)
);

CREATE TABLE USER_PREFERENCES
(
  Preference_ID INT IDENTITY(1,1) NOT NULL,
  Setting_Name VARCHAR(20) NOT NULL,
  Setting_Value VARCHAR(20) NOT NULL,
  User_ID INT NOT NULL,
  PRIMARY KEY (Preference_ID),
  FOREIGN KEY (User_ID) REFERENCES [USER](User_ID)
);

CREATE TABLE USER_PAYMENT_METHOD
(
  Payment_Method_ID INT IDENTITY(1,1) NOT NULL,
  Card_Holder_Name VARCHAR(100) NOT NULL,
  Last_4_Digits CHAR(4) NOT NULL,
  Card_Type VARCHAR(20) NOT NULL,
  Expiry_Date DATE NOT NULL,
  User_ID INT NOT NULL,
  PRIMARY KEY (Payment_Method_ID),
  FOREIGN KEY (User_ID) REFERENCES [USER](User_ID)
);

CREATE TABLE SERVICE_TYPE
(
  Service_Type_ID INT IDENTITY(1,1) NOT NULL,
  Description VARCHAR(255) NOT NULL,
  Service_Type_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (Service_Type_ID)
);

CREATE TABLE TRIP
(
  Trip_ID INT IDENTITY(1,1) NOT NULL,
  Request_Time DATETIME NOT NULL,
  Status VARCHAR(50) NOT NULL,
  Start_Point GEOGRAPHY NOT NULL,
  End_Point GEOGRAPHY NOT NULL,
  User_ID INT NOT NULL,
  Service_Type_ID INT NOT NULL,
  PRIMARY KEY (Trip_ID),
  FOREIGN KEY (User_ID) REFERENCES [USER](User_ID),
  FOREIGN KEY (Service_Type_ID) REFERENCES SERVICE_TYPE(Service_Type_ID)
);

CREATE TABLE PAYMENT_TRANSACTION
(
  Payment_ID INT IDENTITY(1,1) NOT NULL,
  Gross_Amount DECIMAL(10,2) NOT NULL,
  Status VARCHAR(30) NOT NULL,
  Created_At DATETIME NOT NULL,
  User_ID INT NOT NULL,
  Payment_Method_ID INT NOT NULL,
  Trip_ID INT NOT NULL,
  PRIMARY KEY (Payment_ID),
  FOREIGN KEY (User_ID) REFERENCES [USER](User_ID),
  FOREIGN KEY (Payment_Method_ID) REFERENCES USER_PAYMENT_METHOD(Payment_Method_ID),
  FOREIGN KEY (Trip_ID) REFERENCES TRIP(Trip_ID)
);

CREATE TABLE GDPR_LOG
(
  GDPR_ID INT IDENTITY(1,1) NOT NULL,
  Comments VARCHAR(200) NOT NULL,
  Status VARCHAR(50) NOT NULL,
  Requested_At DATETIME NOT NULL,
  Approved_At DATETIME NULL,
  User_ID INT NOT NULL,
  PRIMARY KEY (GDPR_ID),
  FOREIGN KEY (User_ID) REFERENCES [USER](User_ID)
);

CREATE TABLE DRIVER
(
  User_ID INT NOT NULL,
  Photo VARBINARY(255) NOT NULL,
  EU_Residence_Pass VARCHAR(50) NOT NULL,
  Status VARCHAR(50) NOT NULL,
  PRIMARY KEY (User_ID),
  FOREIGN KEY (User_ID) REFERENCES [USER](User_ID)
);

CREATE TABLE DRIVER_DOC_TYPE
(
  Doc_Type_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (Doc_Type_Name)
);

CREATE TABLE DRIVER_DOCUMENT
(
  Driver_Document_ID INT IDENTITY(1,1) NOT NULL,
  Status VARCHAR(50) NOT NULL,
  Expiry_Date DATE NOT NULL,
  Issue_Date DATE NOT NULL,
  Uploaded_At DATETIME NOT NULL,
  File_Data VARBINARY(255) NOT NULL,
  User_ID INT NOT NULL,
  Doc_Type_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (Driver_Document_ID),
  FOREIGN KEY (User_ID) REFERENCES DRIVER(User_ID),
  FOREIGN KEY (Doc_Type_Name) REFERENCES DRIVER_DOC_TYPE(Doc_Type_Name)
);

CREATE TABLE GEOFENCE_REGION
(
  Region_ID INT IDENTITY(1,1) NOT NULL,
  Name VARCHAR(50) NOT NULL,
  Region_Polygon GEOGRAPHY NOT NULL,
  PRIMARY KEY (Region_ID)
);

CREATE TABLE VEHICLE
(
  License_Plate VARCHAR(10) NOT NULL,
  Seat_Capacity INT NOT NULL,
  Trunk_Space FLOAT NOT NULL,
  Trunk_Weight FLOAT NOT NULL,
  Vehicle_Type VARCHAR(50) NOT NULL,
  Price_To_Ride DECIMAL(10,2) NOT NULL,
  Status VARCHAR(50) NOT NULL,
  User_ID INT NOT NULL,
  Region_ID INT NOT NULL,
  PRIMARY KEY (License_Plate),
  FOREIGN KEY (User_ID) REFERENCES DRIVER(User_ID),
  FOREIGN KEY (Region_ID) REFERENCES GEOFENCE_REGION(Region_ID)
);

CREATE TABLE VEHICLE_LOCATION
(
    License_Plate VARCHAR(10) NOT NULL,
    GeoPoint GEOGRAPHY NOT NULL,
    Updated_At DATETIME NOT NULL DEFAULT GETDATE(),
    PRIMARY KEY (License_Plate),
    FOREIGN KEY (License_Plate) REFERENCES VEHICLE(License_Plate)
);


CREATE TABLE VEHICLE_PHOTO
(
  Photo_ID INT IDENTITY(1,1) NOT NULL,
  Photo VARBINARY(255) NOT NULL,
  License_Plate VARCHAR(10) NOT NULL,
  PRIMARY KEY (Photo_ID),
  FOREIGN KEY (License_Plate) REFERENCES VEHICLE(License_Plate)
);

CREATE TABLE VEHICLE_DOC_TYPE
(
  Doc_Type_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (Doc_Type_Name)
);

CREATE TABLE VEHICLE_DOCUMENT
(
  Vehicle_Document_ID INT IDENTITY(1,1) NOT NULL,
  Status VARCHAR(50) NOT NULL,
  Expiry_Date DATE NOT NULL,
  Issue_Date DATE NOT NULL,
  Uploaded_At DATETIME NOT NULL,
  File_Data VARBINARY(MAX) NOT NULL,
  License_Plate VARCHAR(10) NOT NULL,
  Doc_Type_Name VARCHAR(50) NOT NULL,
  PRIMARY KEY (Vehicle_Document_ID),
  FOREIGN KEY (License_Plate) REFERENCES VEHICLE(License_Plate),
  FOREIGN KEY (Doc_Type_Name) REFERENCES VEHICLE_DOC_TYPE(Doc_Type_Name)
);

CREATE TABLE BRIDGE_POINT
(
  Bridge_ID INT IDENTITY(1,1) NOT NULL,
  Bridge_Location GEOGRAPHY NOT NULL,
  PRIMARY KEY (Bridge_ID)
);

CREATE TABLE BRIDGE_REGION_MAP
(
  Region_ID INT NOT NULL,
  Bridge_ID INT NOT NULL,
  PRIMARY KEY (Region_ID, Bridge_ID),
  FOREIGN KEY (Region_ID) REFERENCES GEOFENCE_REGION(Region_ID),
  FOREIGN KEY (Bridge_ID) REFERENCES BRIDGE_POINT(Bridge_ID)
);

CREATE TABLE SERVICE_CATALOG
(
  Catalog_ID INT IDENTITY(1,1) NOT NULL,
  Available_From DATETIME NOT NULL,
  Available_To DATETIME NOT NULL,
  License_Plate VARCHAR(10) NOT NULL,
  User_ID INT NOT NULL,
  Service_Type_ID INT NOT NULL,
  PRIMARY KEY (Catalog_ID),
  FOREIGN KEY (License_Plate) REFERENCES VEHICLE(License_Plate),
  FOREIGN KEY (User_ID) REFERENCES DRIVER(User_ID),
  FOREIGN KEY (Service_Type_ID) REFERENCES SERVICE_TYPE(Service_Type_ID)
);

CREATE TABLE TRIP_VEHICLE_MATCH
(
  Match_ID INT IDENTITY(1,1) NOT NULL,
  Offer_Time DATETIME NOT NULL,
  Response_Time DATETIME NOT NULL,
  Response_Status VARCHAR(30) NOT NULL,
  Trip_ID INT NOT NULL,
  License_Plate VARCHAR(10) NOT NULL,
  PRIMARY KEY (Match_ID),
  FOREIGN KEY (Trip_ID) REFERENCES TRIP(Trip_ID),
  FOREIGN KEY (License_Plate) REFERENCES VEHICLE(License_Plate)
);

CREATE TABLE TRIP_SEGMENT
(
  Segment_ID INT IDENTITY(1,1) NOT NULL,
  Sequence_No INT NOT NULL,
  Start_Point GEOGRAPHY NOT NULL,
  End_Point  GEOGRAPHY NOT NULL,
  Trip_ID INT NOT NULL,
  License_Plate VARCHAR(10) NOT NULL,
  PRIMARY KEY (Segment_ID),
  FOREIGN KEY (Trip_ID) REFERENCES TRIP(Trip_ID),
  FOREIGN KEY (License_Plate) REFERENCES VEHICLE(License_Plate)
);

CREATE TABLE VEHICLE_REQUIREMENTS
(
  Requirement_ID INT IDENTITY(1,1) NOT NULL,
  Min_Seats INT NOT NULL,
  Max_Vehicle_Age INT NOT NULL,
  Min_Trunk_Space FLOAT NOT NULL,
  Min_Trunk_Weight FLOAT NOT NULL,
  Must_Be_4_Door BINARY(1) NOT NULL,
  Must_Have_Rear_Seats BINARY(1) NOT NULL,
  Required_Vehicle_Type VARCHAR(50) NOT NULL,
  Service_Type_ID INT NOT NULL,
  PRIMARY KEY (Requirement_ID),
  FOREIGN KEY (Service_Type_ID) REFERENCES SERVICE_TYPE(Service_Type_ID)
);