USE OSRH;
GO

DROP TABLE IF EXISTS TRIP_SEGMENT;
DROP TABLE IF EXISTS TRIP_VEHICLE_MATCH;
DROP TABLE IF EXISTS SERVICE_CATALOG;
DROP TABLE IF EXISTS BRIDGE_REGION_MAP;
DROP TABLE IF EXISTS BRIDGE_POINT;
DROP TABLE IF EXISTS VEHICLE_DOCUMENT;
DROP TABLE IF EXISTS VEHICLE_PHOTO;  
DROP TABLE IF EXISTS VEHICLE;
DROP TABLE IF EXISTS VEHICLE_REQUIREMENTS;
DROP TABLE IF EXISTS DRIVER_DOCUMENT;
DROP TABLE IF EXISTS DRIVER;
DROP TABLE IF EXISTS GDPR_LOG;
DROP TABLE IF EXISTS PAYMENT_TRANSACTION;
DROP TABLE IF EXISTS TRIP;
DROP TABLE IF EXISTS SERVICE_TYPE;
DROP TABLE IF EXISTS USER_PAYMENT_METHOD;
DROP TABLE IF EXISTS USER_PREFERENCES;
DROP TABLE IF EXISTS AUTHENTICATION;
DROP TABLE IF EXISTS GEOFENCE_REGION;
DROP TABLE IF EXISTS [USER];
DROP TABLE IF EXISTS USER_TYPE;
